config/routes.rb
Rails.application.routes.draw do
  resources :tags
  get 'search', to: 'search#index'
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :books do 
    resources :reviews
    resources :contents
  end

  root 'books#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord  
    belongs_to :user
    belongs_to :category
    has_many :reviews, dependent: :destroy
    has_many :content, dependent: :destroy
    has_many :taggables, dependent: :destroy
    has_many :tags, through: :taggables

    # validates :title, presence: true, length: { maximum: 7 }
    # validates :description, presence: true
    # validates :author, presence: true, length: { maximum: 20 }

    has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/content.rb
class Content < ApplicationRecord
    belongs_to :book
    belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :user

    ratyrate_rateable "reviews"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggables, dependent: :destroy
    has_many :books, through: :taggables
end

app/models/taggable.rb
class Taggable < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :content, dependent: :destroy

  ratyrate_rater
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: :index
    
    # after_action :verify_authorized, except: :index
    # after_action verify_policy_scoped, only: :index

    def index
        policies = policy_scope(Book)
        
        if params[:category].blank?
            @books = Book.order("created_at DESC")
        else
            @category = Category.find_by(name: params[:category])
            @books = @category.books
        end
    end

    def new
        @book = current_user.books.build
        @categories = Category.pluck(:name, :id)
    end

    def create      
       

        if @book = Book.create(book_params)
          redirect_to root_path
        else
          render 'new'
        end
      end

    def edit
        @categories = Category.pluck(:name, :id)
    end

    def update 
     

        @book.category_id = params[:category_id]
        @book = Book.find(params[:id])
        authorize @book
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end
    
    def destroy
        @book.destroy
        redirect_to root_path
    end

    private

  
    def book_params
        params.require(:book).permit(:title, :description, :author,:category_id, :book_img, :tags).merge(user_id: current_user.id)
        end

    def find_book
        @book = Book.find(params[:id])
        authorize @book 
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy]

    def new
        @review = Review.new 
    end

    def create
        @review = Review.new(review_params)
        @review.book_id = @book.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
    
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to book_path(@book)
    end

    private

    def review_params
        params.require(:review).permit(:rating, :comment)
    end

    def find_book
        @book = Book.find(params[:book_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Book.ransack(params[:q])
    @books = @query.result(distinct: true)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, html: { multipart: true } do |f| %>
    <%= f.input :category_id do %>
      <%= f.select :category_id, Category.all.map{|c| [c.name,c.id]}, :prompt => "Select a category" %> 
    <% end %>
    
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, as: :text%>
    <%= f.input :author %>
    <%= f.input :category_id %>
    <%= f.button :submit, :class => 'btn-custom2' %>
   
  <% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

    <div class="edit-book-form">

      <h1>Edit Book</h1>

      <%= simple_form_for @book, :html => { :multipart => true } do |f| %>
          <%= f.select :category_id, @categories %>
          <%= f.file_field :book_img %>
          <%= f.input :title, label: "Book Title" %>
          <%= f.input :description%>
          <%= f.input :author %>
          <%= f.button :submit, :class => "btn-custom2" %>
        <% end %>
    
      </div>

</div>

app/views/books/index.html.erb
<h3>Tags</h3>
<% Category.all.each do |category| %>
	|<%= link_to category.name, books_path(category: category.name), class: "link" %>|    
<% end %>
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>

	<h1>There are no books currently in this category</h1>

<% else %>	

	<div class="row">

		<% @books.each do |book| %>

			<div class="col-md-3">
				<a href="/books/<%= book.id %>">
					<%= image_tag book.book_img.url(:book_index), class: "book" %>
				</a>
			</div>	

		<% end %>

	</div>
	
<% end %>
	
<%= link_to "Add Book", new_book_path %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

    <div class="new-book-form">
        
        <h1>New Book</h1>

        <%= render 'form' %>
    
    </div>

</div>

app/views/books/show.html.erb
<div class="row">
    
    <div class="col-md-4"> 
        <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
    </div>
    
    <div class="col-md-8">

        <div class="book-info">
        
            <h2 class="book-title"><%= @book.title %></h2>
            <h3 class="book-author"><span>Author :</span> <%= @book.author %></h3>
            <h2 class="avg-rating">Average Rating</h2>
            <div class="average-review-rating" data-score=<%= @average_review %>></div>
            <span class="number-of-reviews" >Based on <%= @book.reviews.count %> reviews</span>
            <p class="book-description"><%= @book.description %></p>
        
        </div>
    </div>

    <div class="row">
    
    <div class="col-md-5">

        <div class="reviews">

            <h1>Reviews</h1>
            <%= render @book.reviews %>

            <div>
                <%= link_to "Add Rreview", new_book_review_path(@book), class: "btn-custom" %>
            </div> 
       
        </div>   
    </div>

</div>
        
</div>

<div class="row">
    
    <div class="col-md-3">

        <div class="reviews">

            <h1>Table of Content</h1>
            <%= render @book.content %>

            <div class="col-md-4">
                <%= link_to "AddContent", new_book_content_path(@book), class: "btn-custom" %>
            </div> 
       
        </div>   
    </div>

</div>

<div class="links btn-group">

    <%= link_to "Back", root_path, class: "btn btn-custom" %>

    <% if user_signed_in? %>

        <% if @book.user_id == current_user.id %>
            
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom"  if policy(@book).update?  %>    
            <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" if policy(@book).destroy?%> 

        <% end %>

    <% end %>

</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/tags/_form.html.erb
<%= simple_form_for(@tag) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>